### ISSUE TITLE
Adding functionality

### ISSUE THREAD

**Issue by slackmoehrle** [gregtinkers/carspeed.py#5]
I've been running `carspeed.py` for a few months, capturing the cars speed as they drive by. I added some functionality to write each car out to a .csv. I worked with local law enforcement and started giving them the data. They used it find times that would be good to patrol and catch speeders. There was a car that routinely was going down my road at about the same time at a high rate of speed. They patrolled and caught the car doing 80 in a 35. What a huge ticket. Now they are using the data to get the budget for extra patrolling units.

I want to add more functionality and I hope that we can discuss it a bit. I would like to add the ability to also know the make and model of the car. This involves a lot.
1. Use a deep learning box running a few GTX Titan X cards. Cuda, cuDNN, OpenCV.
2. Need cars pics to train the NN

Shall we discuss how we can accomplish this?

**Comment by gregtinkers** [comment]
@slackmoehrle Woot! You caught a bad guy!

I really don't want to be Debbie Downer, but identifying the make and model will not be an easy task. Here's a link to one effort by a major insurance company using, I assume, some major hardware. https://www.wired.com/2014/12/app-can-instantly-identify-car-least-half-time/ 
The issue is that carspeed captures a side view of a car and training OpenCV to distinguish the side images would require a huge training effort. 

If you are looking for better identification of the vehicle, perhaps capturing an image of the rear of the cars that pass by and correlating that to the carspeed results and using the State Farm app to do the identification of speeder would be possible.

You've presented and interesting challenge to the community. Let's see if anyone else has any suggestions.

**Comment by slackmoehrle** [comment]
@gregtinkers I'n not naive to the challenges. Thanks for the link, let me have a look see.

I was thinking that this might involve more than one camera. I have a few telephone poles outside my house that I could mount additional hardware on. Then I could have a number of angles.

**Comment by RawLiquid** [comment]
Just curious where you live that you got LE interested in the data?

**Comment by slackmoehrle** [comment]
@RawLiquid I live in the Finger Lakes region of Upstate NY. We don't have a
local police force so we rely on the county Sheriff and the State Police. I
started collecting each car in a .csv and at the end of the month suck it
into Excel and tidy it up so that it makes sense to those looking at it.
Note the obvious times there are excessive speeders, repeatedly with some
graphs and charts.

**Comment by slackmoehrle** [comment]
Does anyone have ideas about IP based cameras? Something weather proof. I think Point Blank makes a variety of cameras.

I was thinking that I could read the video stream coming from the camera and as cars pass thru the designated area I can capture the rear of the car and use that image to determine what kind of car it is.

Now to get some starting data I could visit a number of dealerships in my area (they are all lined up on a single street) and take pictures of the rears using my phone. Would probably take me a few hours to do this and seems easy enough to do. Chances are they have current model year and at least a few of the previous model years. I stopped at my local Subaru dealer a few days ago and they have 2014, 2015, 2016 and 2017 of several models of cars.

**Comment by Choroid** [comment]
Take a look at some of Ubiquiti's outdoor camera offerings.

https://www.ubnt.com/unifi-video/unifi-video-camera-g3/

or

https://www.ubnt.com/unifi-video/unifi-video-camera-pro/

**Comment by slackmoehrle** [comment]
Thanks.
